# Generated by Django 2.2.2 on 2019-06-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='str', unique=True),
            preserve_default=False,
        ),
    ]
